//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐỒ_ÁN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_VanPhongPhamEntities : DbContext
    {
        public QL_VanPhongPhamEntities()
            : base("name=QL_VanPhongPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public DbSet<tblDanhGia> tblDanhGia { get; set; }
        public DbSet<tblGioHang> tblGioHang { get; set; }
        public DbSet<tblHinhAnh> tblHinhAnh { get; set; }
        public DbSet<tblHoaDon> tblHoaDon { get; set; }
        public DbSet<tblKhachHang> tblKhachHang { get; set; }
        public DbSet<tblLoaiSP> tblLoaiSP { get; set; }
        public DbSet<tblNhaCungCap> tblNhaCungCap { get; set; }
        public DbSet<tblNhanVien> tblNhanVien { get; set; }
        public DbSet<tblSanPham> tblSanPham { get; set; }
        public DbSet<tblTinhTrang> tblTinhTrang { get; set; }
        public DbSet<tblVaiTro> tblVaiTro { get; set; }
    }
}
