//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐỒ_ÁN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhGia
    {
        public int ID { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
