//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐỒ_ÁN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhachHang
    {
        public tblKhachHang()
        {
            this.tblDanhGia = new HashSet<tblDanhGia>();
            this.tblGioHang = new HashSet<tblGioHang>();
            this.tblHoaDon = new HashSet<tblHoaDon>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string MatKhau { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string Avarta { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<tblDanhGia> tblDanhGia { get; set; }
        public virtual ICollection<tblGioHang> tblGioHang { get; set; }
        public virtual ICollection<tblHoaDon> tblHoaDon { get; set; }
    }
}
