//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐỒ_ÁN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        public tblSanPham()
        {
            this.tblChiTietHoaDon = new HashSet<tblChiTietHoaDon>();
            this.tblDanhGia = new HashSet<tblDanhGia>();
            this.tblGioHang = new HashSet<tblGioHang>();
            this.tblHinhAnh = new HashSet<tblHinhAnh>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string ThuongHieu { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTaChiTiet { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        public Nullable<int> NCC { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual ICollection<tblDanhGia> tblDanhGia { get; set; }
        public virtual ICollection<tblGioHang> tblGioHang { get; set; }
        public virtual ICollection<tblHinhAnh> tblHinhAnh { get; set; }
        public virtual tblLoaiSP tblLoaiSP { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
    }
}
